version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - sam --version
      - aws iam list-users
      - aws configure list
  build:
    commands:
      # - aws cloudformation package --template template.yaml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
      # - aws cloudformation deploy --template-file template-export.yml --s3-bucket $S3_BUCKET --stack-name $STACKNAME --capabilities CAPABILITY_IAM --region $REGION --parameter-overrides Env=$ENV
      - sam build
      - sam package --s3-bucket lswn-java-sam-test --output-template-file packaged.yaml
artifacts:
  type: zip
  files:
    - template-export.yml
