version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "codebuild-sam-test"
s3_bucket = "codepipeline-ap-northeast-1-313727829930"
s3_prefix = "sam-codepipeline-tes/SourceArti"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Env=\"dev\""
